### ISSUE TITLE
Do you really need package for that?

### ISSUE THREAD

**Issue by Slava** [peerlibrary/meteor-util#1]
At least on linker branch following works without any packages:

```
if (Meteor.isServer) {
  Meteor.startup(function () {
    console.log(Npm.require('util').format);
  });
}

```

**Comment by mitar** [comment]
Probably not really. It was more needed before 0.6. But it is useful to have a package if you want to add client-side at some point. So yes, it could be done differently. But I see it nicer to use package manager than to use `Npm.require` in the app code. They told me I should not be really using `Npm.require` in the app code.

**Comment by Slava** [comment]
That's true, I just was wondering :)

(Shame on me, I use Npm.require for fibers, futures, util, path and other stuff in my code)

**Comment by mitar** [comment]
Yes. I started using it now as well. So before `Npm.require` I didn't want to use `Meteor.__require__` directly in the code and I moved everything to packages. Now I am getting lazy as well. Especially because using the package puts things into global namespace. And by using `Npm.require` you can bind it locally. To just the scope you need. So there is some use of it.

**Comment by mitar** [comment]
I will cleanup probably this things once Meteor settles down on the packages and other relevant stuff. I already spent too much time changing the code because Meteor is changing things under me.
